// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD1r9AruPLoKVnRe1rIVDjzyy6cjPDAjaA',
    appId: '1:892180106307:web:85b707736fc91446d458f6',
    messagingSenderId: '892180106307',
    projectId: 'gabrielsaturi-firebase-app',
    authDomain: 'gabrielsaturi-firebase-app.firebaseapp.com',
    storageBucket: 'gabrielsaturi-firebase-app.appspot.com',
    measurementId: 'G-1ZMD9LT1QJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyANhIgniBzgPyw8b-l8N-ODMf6NN7E0xKQ',
    appId: '1:892180106307:android:c85ff36bf9ac70e3d458f6',
    messagingSenderId: '892180106307',
    projectId: 'gabrielsaturi-firebase-app',
    storageBucket: 'gabrielsaturi-firebase-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAkYX8UhgY4MnxoYoMYqnkKbCkeoCBYfrQ',
    appId: '1:892180106307:ios:10c2a32094680820d458f6',
    messagingSenderId: '892180106307',
    projectId: 'gabrielsaturi-firebase-app',
    storageBucket: 'gabrielsaturi-firebase-app.appspot.com',
    iosBundleId: 'com.example.firebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAkYX8UhgY4MnxoYoMYqnkKbCkeoCBYfrQ',
    appId: '1:892180106307:ios:10c2a32094680820d458f6',
    messagingSenderId: '892180106307',
    projectId: 'gabrielsaturi-firebase-app',
    storageBucket: 'gabrielsaturi-firebase-app.appspot.com',
    iosBundleId: 'com.example.firebase',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD1r9AruPLoKVnRe1rIVDjzyy6cjPDAjaA',
    appId: '1:892180106307:web:f409d394d9bbc84fd458f6',
    messagingSenderId: '892180106307',
    projectId: 'gabrielsaturi-firebase-app',
    authDomain: 'gabrielsaturi-firebase-app.firebaseapp.com',
    storageBucket: 'gabrielsaturi-firebase-app.appspot.com',
    measurementId: 'G-5KYVPG4GEP',
  );

}